import assert from 'node:assert/strict';
import {createResultStore} from '../src/result-store.js';
import {connectBackend,disconnectBackend,backendAvailable,backendHeaders,normalizeEndpoint} from '../src/runtime-config.js';
let message='',downloads=0,events=0;
const bytes=new Uint8Array([1,2,3]);
let failure='AbortError';
const store=createResultStore({onChange:()=>events++,onStatus:s=>message=s,picker:()=>{throw new DOMException('test',failure);},download:async()=>{downloads++;}});
store.set(bytes,'sample.vfm');const item=store.current;
await store.saveAs();assert.match(message,/Chưa lưu/);assert.equal(store.current,item);assert.equal(downloads,0);
failure='SecurityError';await store.saveAs();assert.match(message,/Tải xuống thông thường/);assert.equal(downloads,0);
await store.download();await store.download();assert.equal(downloads,2);assert.deepEqual(new Uint8Array(await store.current.blob.arrayBuffer()),bytes);
store.clear();assert.equal(store.current,null);await store.download();assert.equal(downloads,2);assert.equal(events,2);
let written;
const successful=createResultStore({picker:()=>({createWritable:async()=>({write:async b=>written=b,close:async()=>{}})})});successful.set(bytes,'sample.vfm');await successful.saveAs();assert.deepEqual(new Uint8Array(await written.arrayBuffer()),bytes);
assert.throws(()=>normalizeEndpoint('http://example.com'));assert.throws(()=>normalizeEndpoint('https://token@example.com'));assert.throws(()=>normalizeEndpoint('https://example.com/?token=x'));
assert.equal(backendAvailable(),false);
await assert.rejects(connectBackend('https://example.com','',()=>{}));
await assert.rejects(connectBackend('https://example.com','sample',async()=>Response.json({ok:true})));
await connectBackend('https://example.com','sample',async(url,opts)=>{assert.equal(opts.headers.Authorization,'Bearer sample');return Response.json({service:'xulyVFM',ok:true,gdal:true});});assert.equal(backendAvailable(),true);assert.equal(backendHeaders().Authorization,'Bearer sample');disconnectBackend();assert.equal(backendAvailable(),false);assert.deepEqual(backendHeaders(),{});
console.log('PASS: cancellation retains bytes, no automatic download on cancel, security fallback, repeated download, successful save, backend fail-closed connection.');
